export const BASIC_GRIDS = [
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
  [
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
    { status: "", type: "" },
  ],
];

export const DEAD_ROW = [
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
  { status: "seized", type: "dead" },
];
