export const BASIC_GRIDS = [
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ],
  [
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' },
    { status: '', type: '' }
  ]
]
